### ISSUE TITLE
Unchecked mallocs

### ISSUE THREAD

**Issue by daveyc** [alisdair/jsmn-example#4]
Can I suggest that you put some log_die() functions around the malloc/realloc functions. On my system memory allocation is set for each process with a initial max of 32MB and mallocs do fail.

**Comment by alisdair** [comment]
I don't know of any unchecked mallocs. They should all be checked with `log_null`. Pull request welcome if I missed some.

**Comment by daveyc** [comment]
buf_tostr() has one. I'm to lazy to clone.

BTW, good work! Your examples are great.

**Comment by alisdair** [comment]
Whoops! Thanks for spotting that. Fixed now.

**Comment by daveyc** [comment]
No worries mate! I'm old school in that I use xmalloc wrappers that die on OOM. That way I don't need to worry about checking each allocation. Not good for production systems but simple and adequate for most cases.
